version: '3.8'

services:
  parthbe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parthbe-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=193.38.235.104;Port=5432;Database=postgres;Username=postgres;Password=8uJr0iBHR6rPzQMooQmMU9UAEuYxktVn4R3G888R2igek4IIA5lADhKfczcYtzQm
      - Jwt__Key=your-super-secret-key-at-least-32-characters-long-for-jwt-signing!!!
      - Jwt__Issuer=EquipmentBookingApp
      - Jwt__Audience=EquipmentBookingUsers
    restart: unless-stopped
    networks:
      - parthbe-network

networks:
  parthbe-network:
    driver: bridge
